### ISSUE TITLE
How to specify output folder?

### ISSUE THREAD

**Issue by BumbuKhan** [primer/primer-module-build#11]
I found it in `build.js`

```
const sourceFile = `${process.cwd()}/${str}`
const outputFile = `${process.cwd()}/build/build.css`
```

so why output folder is hardcoded?

**Comment by muan** [comment]
You're right, there is currently no way to specify the output folder. I think we just didn't think to do it. I think adding a backwards compatible way to specify output directory would be good. Perhaps just default to `./build/build.css` when `--output` isn't passed in.
